name: Android CI (Gerar APK)

on:
  push:
    branches: [ "main" ] # Altere para "master" se for o nome da sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do C처digo
      uses: actions/checkout@v4

    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        java-version: '17' # Vers찾o padr찾o para projetos Android modernos
        distribution: 'temurin'
        cache: gradle

    - name: Dar permiss찾o ao Gradle
      run: chmod +x gradlew

    - name: Compilar APK de Debug
      run: ./gradlew assembleDebug

    - name: Fazer Upload do APK (v4)
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
